package com.gulecugurcan.soapwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-08T19:38:29.290+03:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://www.gulecugurcan.com/soapwebservice", name = "CountriesPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CountriesPort {

    @WebMethod
    @WebResult(name = "getCountryResponse", targetNamespace = "http://www.gulecugurcan.com/soapwebservice", partName = "getCountryResponse")
    public GetCountryResponse getCountry(

        @WebParam(partName = "getCountryRequest", name = "getCountryRequest", targetNamespace = "http://www.gulecugurcan.com/soapwebservice")
        GetCountryRequest getCountryRequest
    );
}
